# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
title: STAT 530
author: Bo Yuan
logo: logo.png

execute:
  execute_notebooks: auto

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/boyuan99/stat530-bioinformatics
  branch: gh-pages
  path_to_book: "."

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

baseurl: /stat530-bioinformatics
